version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "cd backend/ && npm run start"
    ports:
      - '3333:3333'
      - '4444:4444'
    depends_on:
      - database
    volumes:
      - ./:/usr/app/
  database:
    image: mongo
    volumes:
      - database-data:/data/db
volumes:
  database-data: