version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "cd backend/ && npm run start"
    ports:
      - '3333:3333'
    depends_on:
      - database
    volumes:
      - ./:/usr/app/
    networks:
      - default 
  database:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - database-data:/data/db
    networks:
      - default
volumes:
  database-data: