version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    ports:
      - '3333:3333'
    depends_on:
      - database
    volumes:
      - ./backend:/usr/app/backend
  database:
    image: mongo
    volumes:
      - database-data:/data/db
volumes:
  database-data: