version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    depends_on:
      - database
  database:
    image: mongo
    volumes:
      - database-data:/data/db
volumes:
  database-data: